version: '3'

services:

  proxy:
    depends_on: 
      - frontend
    image: patricksyoung/mosaic-proxy:1.1
    ports:
      - '80:80'
    networks:
      - mosaic-network

  frontend:
    image: patricksyoung/mosaic-frontend:latest
    networks:
      - mosaic-network

  backend:
    image: patricksyoung/mosaic-backend:1.1
    depends_on:
      - api
    volumes:
      - mosaic-volume:/var/lib/video
    networks:
      - mosaic-network

  api:
    image: patricksyoung/mosaic-api:1.4
    volumes:
      - mosaic-volume:/var/lib/video
    networks:
      - mosaic-network

volumes:
  mosaic-volume:

networks:
  mosaic-network:
    driver: bridge # a user defined bridge is required; the default bridge network doesn't support name resolution

